In [11]:
def test():
    print("Test() for the function")
    return
test()

Test() for the function


In [9]:
class Demo:
    def test(self):
        print("test() for the class and method")

        return    
obj= Demo()
obj.test()

test() for the class and method


In [13]:
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        
        return fact
p1=Demo1()
print(p1.fact(5))

120


In [20]:
class Demo2:
    def Accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(self):
        print("a=",a)
        print("b=",b)
c1=Demo2
c1.Accept(10,20)
c1.display()
    

TypeError: Accept() missing 1 required positional argument: 'p2'

In [29]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200)) 

300


In [35]:
class Person(object):
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
    
class Employee(Person):
    def isEmployee(self):
        return True
emp=Person("madhuri")
print(emp.getName(),emp.isEmployee())
emp1=Employee("mahema")
print(emp1.getName(),emp1.isEmployee())
    

madhuri False
mahema True


In [36]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [12]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [38]:
import numpy as np
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int64


In [42]:
lst=[1.0,0.2,5.6,7.5,3.2]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(5,)
float64


In [46]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [47]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [51]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [52]:
a1=np.random.normal(5,0.5,10)
print(a1)

[5.12652554 5.64788914 4.91478903 4.9426466  4.73564028 5.3561259
 5.01916625 5.15652639 4.40504878 4.87694278]


In [53]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.zeros(((2,2)),dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [14]:
np.ones(((4,3)),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [17]:
A=np.matrix(np.ones((4,5),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1  1]
 [ 1  1  1 14  1]
 [ 1  1  1  1  1]
 [ 1  1  1 16  1]]
